#!/bin/bash
. /etc/rc.d/init.d/functions
LOG_BASE="/chj/data/log"
APP_BASE="/chj/app"
ProjectName="devops-bmc-api"
projectName="devops-bmc-api"
pidFile="${LOG_BASE}/${ProjectName}/${projectName}.pid"
cpucount=$(cat /proc/cpuinfo| grep "processor"| wc -l)
listen="0.0.0.0:5000"
#gunic=$(rpm -qa |grep gunicorn)
prog=${ProjectName}
accesslogfile="${LOG_BASE}/${ProjectName}/devops-bmc-api-access.log"
errorlogfile="${LOG_BASE}/${ProjectName}/devops-bmc-api-error.log"

gunic="/usr/local/bin/gunicorn"

if (( $# <= 0 )); then
    echo "./console start 启动服务"
    echo "./console stop 停止服务"
    echo "./console restart 重启服务"
    exit 0
fi

function fninstall() {

    if [ ! ${gunic} ] ; then
        yum -y install python36 mysql-devel libxml2* mysql initscripts python36-devel python36-pip python36-setuptools mysql-devel libxml2* mysql initscripts psmisc
        /usr/local/bin/pip3.6 install --upgrade pip
        /usr/local/bin/pip3.6 install --upgrade setuptools
        /usr/local/bin/pip3.6 install requests
        /usr/local/bin/pip3.6 install Jinja2==2.10
        /usr/local/bin/pip3.6 install flask-sqlalchemy
        /usr/local/bin/pip3.6 install gunicorn
        /usr/local/bin/pip3.6 install ansible
        /usr/local/bin/pip3.6 install PyMySQL==0.9.3
        /usr/local/bin/pip3.6 install gql
        /usr/local/bin/pip3.6 install gevent


    fi

}

function fnstart() {

   su ops -c "${gunic} -u ops  -w ${cpucount} --access-logfile ${accesslogfile}   --log-level "debug" --error-logfile ${errorlogfile} -p ${pidFile} -b ${listen} -D boot:app"
    retval=$?
    [ $retval -eq 0 ] && action "Starting $prog: " /bin/true ||action "Starting $prog: " /bin/false
    return $retval
}

function fnstop() {
    su "pkill -f ${pidFile}"
    retval=$?
    [ $retval -eq 0 ] && rm -f ${pidFile} && action "Stopping $prog: " /bin/true||action "Stopping $prog: " /bin/false
    return $retval
}

function fnrestart() {
    fnstop
    sleep 2
    fnstart
}

case $1 in
        start)
            fninstall
            fnstart
    ;;
        stop)
            fnstop
    ;;
        restart)
            fnrestart
    ;;
        install)
            fninstall
    ;;
esac
